spring:
  application:
    name: my-chat-mind
  datasource:
    url: jdbc:postgresql://localhost:5433/jchatmind
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  ai:
    deepseek:
      api-key: your-api-key
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
    zhipuai:
      api-key: your-api-key
      base-url: https://open.bigmodel.cn/api/paas
      chat:
        options:
          model: glm-4.6
    # 无问芯穹 (通过 OpenAI 兼容接口)
    openai:
      api-key: xxxxxxxxxxxx
      base-url: https://cloud.infini-ai.com/maas/coding
      chat:
        options:
          model: kimi-k2.5

  mail:
    host: smtp.qq.com
    port: 587
    username: xxxxx
    password: xxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


mybatis:
  type-aliases-package: com.study.mychatmind.model.entity
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.study.mychatmind.typehandler


ollama:
  base-url: http://localhost:11434
  embedding-model: bge-m3


document:
  storage:
    base-path: ./data/documents





